customCommands:
  - key: "b"
    command: "git browse"
    context: "global"
git:
  commitPrefixes:
  paging:
    colorArg: always
    pager: diff-so-fancy
reporting: "on"
startuppopupversion: 1
refresher:
  refreshInterval: 2
